### ISSUE TITLE
[Feature Request] Rx equivalent bindings for `Store::get` and `Store::fresh`

### ISSUE THREAD

**Issue by mezpahlan** [dropbox/Store#118]
**Is your feature request related to a problem? Please describe.**
`Store::get` and `Store::fresh` allow easy retrieval of a value from the `Store` however it would be nice to have an Rx equivalent to bridge the use case where a project has elected to use RxJava over Coroutines.

**Describe the solution you'd like**
Extension functions on `Store` that return the idiomatic RxJava type but otherwise operate in the same way as `Store::get` and `Store::fresh`.

**Describe alternatives you've considered**
Writing this manually using existing Rx operators such as:

```
// To recreate Store::get(key)
store.observe(StoreRequest(key, refresh = false))
        .filter { it !is StoreResponse.Loading }
        .firstOrError()
        .map { it.requireData() }     
```

**Additional context**
I've forked the project and created a branch for which I am more than happy to submit a PR for but I wanted to discuss this first if this was something you'd be open to. Also I wasn't sure what to do about tests so some guidance there would be appreciated.

https://github.com/mezpahlan/Store/commit/bba706b40a097b7d8c4c065ec92ecaa474841efb

**Comment by digitalbuddha** [comment]
Apologies for delay! Sounds like a great addition. We'd be happy to accept it.  I don't think this would need many tests as you're going to really just be testing the operators.  If you can please copy the `RxSingleTest` to show usage of your proposed api. Thank you for using Store and wanting to improve it!
