### ISSUE TITLE
[Feature Request] How to make KeyedSynchronizer multiplatform

### ISSUE THREAD

**Issue by clhols** [dropbox/Store#135]
What would be the strategy for making KeyedSynchronizer independent of java.util?

**Comment by ychescale9** [comment]
Not familiar with KMP or native concurrency at all, but my impression is you could put these platform-specific implementations (`actual`) into the `jvmMain` source set which can still use `java.util` and have different implementations in `nativeMain` source set, and keep most of the logic in `commonMain` with `expect` definitions?

**Comment by clhols** [comment]
Yes, we could have two different implementations for the JVM and native, but if they are too different then I can be hard to make a common API.

Jetbrains proposes something different from what we are used to on the JVM:
https://github.com/JetBrains/kotlin-native/blob/master/CONCURRENCY.md
