### ISSUE TITLE
[In Progress] Move Cache module to kotlin

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#14]
Currently we are using a forked version of Guava Cache but no longer need a "Loading Cache". Since our api is much smaller, we should rewrite the Cache.  Cache is our last Java module, a rewrite opens up multiplatform support 

We need a cache with the following features
* 100% kotlin
* Allows TTL & Size expiration

**Comment by ychescale9** [comment]
@digitalbuddha I can have a go at this. Could you elaborate on the second requirement? Would this involve changing current APIs?

**Comment by digitalbuddha** [comment]
No changes from current api. Here is the current builder, we would need the same in the new impl: https://github.com/dropbox/Store/blob/1810355341a9d6f2f8dc17e117d3dec31b10407b/store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt#L58

Here is the current interface for usage:
https://github.com/dropbox/Store/blob/1810355341a9d6f2f8dc17e117d3dec31b10407b/cache/src/main/java/com/dropbox/android/external/cache3/Cache.java#L12

We do not need to support the blocking get call which calls a loader.  That was an api that store3 had that is no longer needed. 
```kt
@Nonnull
  V get(K key, Callable<? extends V> valueLoader) throws ExecutionException;
```

Appreciate the help but as a warning we would expect 100% test coverage before accepting the contribution. Current implementation  does not have many tests in repo due it being  taken from Guava which had extensive testing

**Comment by ychescale9** [comment]
Thanks!

**Comment by ychescale9** [comment]
> We do not need to support the blocking get call which calls a loader. That was an api that store3 had that is no longer needed.
> 
> ```kotlin
> @Nonnull
>   V get(K key, Callable<? extends V> valueLoader) throws ExecutionException;
> ```

@digitalbuddha So looks like we do need to support this after all? Currently this is only used by `FileSystemImpl`. Are we planning to use this API anywhere else or even expose it in the `Store` API?

**Comment by yigit** [comment]
for xref: https://github.com/dropbox/Store/issues/89
