### ISSUE TITLE
[BUG] deadlock in memory cache eviction

### ISSUE THREAD

**Issue by jobernolte** [dropbox/Store#152]
**Describe the bug**
When evaluating the library I came across the situation where submitting multiple store requests leads to a deadlock when the memory cache size is exceeded.

**To Reproduce**
My store init:
```
    @OptIn(ExperimentalStdlibApi::class, ExperimentalTime::class)
    private fun initStore(): Store<UserId, User> {
        return StoreBuilder.fromNonFlow<UserId, User> { userId ->
            logger.debug { "store.fetch $userId" }
            requireNotNull(
                sessionManager.invoke<UsersEvent>(
                    GetUsersCommand(data = GetUsersData(userIds = listOf(userId)))
                ).data.users.firstOrNull()
            )
        }.nonFlowingPersister(
            reader = { userId ->
                dataDao.get(userId, User::class)?.also {
                    logger.debug { "persister.read: $userId -> $it" }
                }
            },
            writer = { userId, user ->
                logger.debug { "persister.write: $user" }
                dataDao.put(userId, user)
            },
            delete = { userId ->
                logger.debug { "persister.delete: $userId" }
                dataDao.remove(userId)
            },
            deleteAll = { dataDao.removeAll() }
        ).cachePolicy(
            MemoryPolicy.MemoryPolicyBuilder()
                .setExpireAfterAccess(60.toDuration(DurationUnit.MINUTES))
                .setMemorySize(5).build()
        ).build()
    }
```

My code which concurrently fetches data from the store (my userIds size is about 10):
```
  userIds.map {
                store.stream(StoreRequest.cached(it, refresh = false))
                    .filterNot { response -> response is StoreResponse.Loading }.firstOrNull()
                    ?.dataOrNull()
            }.filterNotNull()
```

**Expected behavior**
I expected that the library is capable of handling many requests.

**Screenshots**
![Anmerkung 2020-04-14 152352](https://user-images.githubusercontent.com/208996/79229840-f83f9500-7e63-11ea-8e42-08a61b18d9e1.png)

**Smartphone (please complete the following information):**

**Additional context**
When I debug the code I can see that there seems to a race condition in RealCache.evictEntries() (see screenshot).

**Comment by jobernolte** [comment]
I further debugged the code and evictEntries() tries without success to remove the first entry of **accessQueue** over and over again.

**Comment by ychescale9** [comment]
Thanks for reporting the issue, will take a look soon. Any chance you can share a repo that reproduces the issue?

**Comment by jobernolte** [comment]
Sorry, I don't have a repo to share. The code is from our app which I can't share. But I think it should be easy to reproduce the bug.

**Comment by ychescale9** [comment]
No problems I'll try to reproduce it with a test.
