### ISSUE TITLE
Experimental Duration APIs vs Backward Compatibility

### ISSUE THREAD

**Issue by tasomaniac** [dropbox/Store#157]
As discussed in #150, we would like to keep TimeUnit based APIs next to Duration for compatibilities reasons 

- Jetbrains has a huge disclaimer about using experimental APIs in libraries since it may introduce binary incompatible changes.
- The usage of annotation propogates to users and make it impossible to call from Java. 

## Proposal

Add TimeUnit based APIs back with deprecation.

**Comment by digitalbuddha** [comment]
closing as we will be kotlin only going forward, sorry for late reply

**Comment by tasomaniac** [comment]
Sounds good. I remember discussing that this will not be done back then.
