### ISSUE TITLE
When should we have the sample app point to released artifacts?

### ISSUE THREAD

**Issue by eyalgu** [dropbox/Store#161]
Should we/ when should we update the sample app to a version rather than referencing the code?

in #123  I've made some big API changes. as part of the diff I updated the sample app to show how the new API will be used (which is helpful for the reviewers).

#159 changed the sample app to reference the last publicly released version of the library. With this change We cannot update the sample app until after we release an API change.

This is probably a desirable state once the API stabilized, which should be very soon, but, while we're still in alpha, we probably want to make API changes as easy for us to push as possible.

I believe this is the last major API change aside from some cleanup before we're ready for beta. Once we're in beta, we can probably re-land #159 

Thoughts?

**Comment by eyalgu** [comment]
cc @DYJParker @yigit @digitalbuddha

**Comment by digitalbuddha** [comment]
Sure, could you change Releasing.MD to have a note to not keep pegged to the internal version for too long. The intent was to have an integration test for released artifacts. We have had versions go out previously that did not publish a module or screwed up an artifact name

**Comment by eyalgu** [comment]
> Sure, could you change Releasing.MD to have a note to not keep pegged to the internal version for too long. The intent was to have an integration test for released artifacts. We have had versions go out previously that did not publish a module or screwed up an artifact name

done

**Comment by yigit** [comment]
i think samples should always reference the source so that it is up to date.
we can always create tags/branches if people need to see the latest release docs.

We need to be able to keep samples up to date w/ the source.

**Comment by sdoward** [comment]
It could be possible to follow something similar to [branch by abstraction ](https://martinfowler.com/bliki/BranchByAbstraction.html#:~:text=%22Branch%20by%20Abstraction%22%20is%20a,change%20is%20still%20in%2Dprogress.&text=We%20change%20that%20section%20of,entirely%20through%20this%20abstraction%20layer.).

This could mean samples live in the corresponding directory. 

- 4.0.0-alpha07/samples
- 4.0.0-beta01/samples

It removes a lot of complexity for maintainers and consumers of the library. Old samples would be deleted when a new version is released. If a consumer needs an old sample they only need to look into the history.

**Comment by digitalbuddha** [comment]
going to keep us pointed to public for now
