### ISSUE TITLE
[BUG] store.get() doesn't call the fetcher when there's no cache

### ISSUE THREAD

**Issue by NapasPayu** [dropbox/Store#165]
```
/**
 * Helper factory that will return data for [key] if it is cached otherwise will return fresh/network data (updating your caches)
 */
suspend fun <Key : Any, Output : Any> Store<Key, Output>.get(key: Key)
```

When I tried on this function, it just returned empty data once.
From my understanding, when store.get() is called and there's no cache, this function should call a fetcher automatically. Is that right? Or I just misunderstood it?

If it is not that way, how should we handle this case? Please help provide a sample of a proper implementation.

**Comment by ychescale9** [comment]
When you said “empty data” did you mean an empty list of whatever the output type of the store is? Sounds like your fetcher can return empty response as normal data which is then cached, so the empty list you get **is** the cached data for that key?

**Comment by NapasPayu** [comment]
@ychescale9 Yes, it is an empty list. However, I have logged network calls. The fetcher is never really called.

**Comment by ychescale9** [comment]
In a normal setup, if it’s returning something it must have originally come from the fetcher.

Can you share your store configuration e.g how you implement the fetcher, source of truth and in memory cache configs etc.

Right now I suspect it’s because your source of truth isn’t able to distinguish between data set being empty VS no data at all. If the reader function returns non-null value regardless of whether it’s empty or not, store will return that as the data for the key and not invoke the fetcher for that request.

**Comment by NapasPayu** [comment]
Here is my code
```
StoreBuilder
            .from<String, List<Taxonomy>, List<Taxonomy>>(
                nonFlowValueFetcher { storeId ->
                    apiService.getTaxonomy(
                        storeId, BUSINESS
                    ).data.taxonomy
                },
                sourceOfTruth = SourceOfTruth.fromNonFlow(
                    reader = { _ -> taxonomyDao.get() },
                    writer = { _, items -> taxonomyDao.insert(items) },
                    deleteAll = taxonomyDao::delete
                )
            )
            .build()
```

```
interface ApiService {
    @POST("q/TaxonomySuperDepts")
    suspend fun getTaxonomy(@Body request: GraphQuery): ApiResult<TaxonomyResult>
}
```

```
@Dao
interface TaxonomyDao {
    @Query("SELECT * FROM taxonomy")
    suspend fun get(): List<Taxonomy>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(taxonomy: List<Taxonomy>)

    @Query("DELETE FROM taxonomy")
    suspend fun delete()
}
```

```
data class TaxonomyResult(
    val taxonomy: List<Taxonomy> = emptyList()
)
```

**Comment by ychescale9** [comment]
Yeah `suspend fun get(): List<Taxonomy>` will always return non-null value so Store always thinks there's existing data from `sourceOfTruth` and therefore not invoke the fetcher.

Try:
```kotlin
reader = { _ -> taxonomyDao.get().ifEmpty { null }  },
```

**Comment by NapasPayu** [comment]
@ychescale9 OK it works!! thanks for your help
