### ISSUE TITLE
[Question] Expectation of Beta release date ?

### ISSUE THREAD

**Issue by titooan** [dropbox/Store#174]
Hi, 
First thank you for your time and your effort building this cool library.
 
I've read about Store and watched [this talk](https://www.youtube.com/watch?v=raWdIwsDe-g), and it seems to be a very good solution. 

I've just started development of an app and I'm wondering if Store is safe to you regarding its current alpha stage. The app we are developing is a kind of medical device, so we need a good stability. It will be released in September.

Is there any expectation of beta release date ?

**Comment by eyalgu** [comment]
Thanks for our interest! We are actually very close to beta. The only thing that's holding us from officially moving to beta is some API stabilization cleanup. #163 and #167 primarily. Stability wise we are in a pretty good place as the initial flow of bug reports from alpha has already died down.

**Comment by NahroTo** [comment]
Now :). I think we can close this issue now.

**Comment by rosariopfernandes** [comment]
A stable version is also out. We can definitely close it :)
