### ISSUE TITLE
[BUG] Fetcher is not executed after initial request despite unique Key.

### ISSUE THREAD

**Issue by es0329** [dropbox/Store#175]
**Description**
Hi. I've built my Store using a GraphQL fetcher and a Room source of truth, both with Coroutines. I use `Int` as the request `Key` to avoid [Apollo](https://github.com/apollographql/apollo-android)'s generated types in my `domain` package. I have an interactor named `GetLesson` exposing API that calls Store's `get` extension.

The UI is a RecyclerView showing `List<Lesson>`. When an item is clicked, `getLesson.run(lesson.id)` begins data loading work.

The first click always completes the entire use-case exactly as expected. But for any later clicks, fetcher and writer are not executed, and then reader always emits the record of the first event.

The only variable request parameter is `lesson.id`. I've confirmed `StoreBuilder` is receiving unique `lesson.id` values with each click. As an experiment, I also converted my request `Key` to use Apollo's generated `LessonQuery` but the issue wasn't solved.

I wonder if I’ve misconfigured something or found something. It’s most likely the first scenario. Does anything stand-out to you that might help my issue? Thanks for your insight; keep up the great work!

**Expected behavior**
A unique request completes Store’s path through fetcher, writer, and reader.

**Smartphone:**
 - Device: OnePlus 5T
 - OS: Android 9
 - Store Version: 4.0.0-alpha06
 - Apollo Version: 2.0.3
 - Room Version: 2.2.5
 - Coroutines Version: 1.3.5

**Additional context**
```
@Dao
abstract class LessonDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun insertLessons(lesson: List<LessonEntity>)

    @Insert
    abstract fun insert(lesson: LessonEntity)

    @Query(LessonSql.QUERY_SELECT_ALL)
    abstract fun loadLessons(): Flow<List<LessonEntity>>

    @Query(LessonSql.QUERY_DELETE_ALL)
    abstract suspend fun deleteAllLessons()
}
```

**Comment by ychescale9** [comment]
Any chance you could share your store configuration?

My guess is you’re running into the same issue as [this](https://github.com/dropbox/Store/issues/165)🙂

**Comment by es0329** [comment]
Thanks @ychescale9! This turned out to be bug a of my own. Sorry for the trouble.
