### ISSUE TITLE
[Question] Fetch collection/detail

### ISSUE THREAD

**Issue by costular** [dropbox/Store#178]
Hi!

I haven't seen a sample nor info in the documentation about this so here comes my question. Should I create two stores: one for the entity collection and another one for the detail?

Imagine a list of users and let's say I wan't to fetch the entire collection but in another screen I just wanna get an user with a specific id.

Thanks!

**Comment by digitalbuddha** [comment]
Do you have one endpoint or two backing the data?

**Comment by costular** [comment]
@digitalbuddha In this case I just have one endpoint which retrieves a small collection but I wanna be able to get a single detail with its id.

**Comment by digitalbuddha** [comment]
I would create 1 store for the list. Then create another store for the detail. The store for the detail can have its own source of truth locally that goes to single entry queries. As for the fetcher, make the single entry fetcher call the allEntryStore.  This way if you ask for a single entry and it is not there it calls the other store which calls the network

**Comment by costular** [comment]
It worked like a charm. Thanks @digitalbuddha!

I'm closing since I resolved it.

**Comment by iceberg1369** [comment]
@costular please provide a sample code
