### ISSUE TITLE
[BUG] Fetcher and SourceOfTruth must now have the same type signatures

### ISSUE THREAD

**Issue by chrisbanes** [dropbox/Store#183]
I'm just updating to alpha06, and hit a bit of a roadblock....

The old API allowed this:

``` kotlin
return StoreBuilder.fromNonFlow<Param, Pair<Result, ExtraInfo> { p: Param ->
    return result to extraInfoWhichPersisterNeeds
}.persister<Param, Result>(
    writer = { (result, extraInfo) ->
        // persist, using the extra info
    }
}
```

But now the `SourceOfTruth` and `Fetcher` need to have the same type signatures, so there's no way to pass along that extra info. Feels a little restrictive to me.

**Comment by digitalbuddha** [comment]
That is not expected/intentional. I can double check tonight what happened. Curious if we can have api checks pick this up.

**Comment by chrisbanes** [comment]
Looking at this again, it seems to be a type inference issue when using a `Unit` key. I can workaround it by explicitly setting the type.

``` kotlin
return StoreBuilder.from(
    fetcher = nonFlowFetcher { _: Unit ->
        /* Need to explicit declare the key type here */
    },
    sourceOfTruth = SourceOfTruth.from(
        writer = { _: Unit, response ->
            /* Need to explicit declare the key's type here */
        }
    )
).build()
```

Closing this! Thanks.

**Comment by digitalbuddha** [comment]
We are about to change the api signatures for the last time https://github.com/dropbox/Store/pull/181 the snapshot is live. I'm hoping to release this as a beta next week
