### ISSUE TITLE
[Feature Request] Source of truth reader should distinguish between the cache read and the final read

### ISSUE THREAD

**Issue by auras** [dropbox/Store#187]
**Is your feature request related to a problem? Please describe.**
I want to distinguish between the first cache read and the final read. Example: I have a store which accepts as a key a list of IDs. Some of the data (for a subset of IDs) is already in cache. For the first read I don't want to return the data if I don't have all the data in cache, but for the 2nd read I should read whatever's in cache, after the data was written to cache. 
Why not return whatever's in cache the 1st time?
Let's go for an example: load data for IDs 1, 2, 1000 where I already have the data for ID 1 in cache. The loading is done with `StoreRequest.cached` (get it from cache if it's there or else get it from network)

1. Check source of truth: only ID 1 is in there. Return null (because listOf(1).size != listOf(1, 2, 1000).size)
2. Get data from network. Only data for 1 and 2 exists and is returned
3. Save data to source of truth: 1 and 2
4. Check source of truth: only ID 1 and 2 are in there. It will return null because listOf(1, 2).size != size(1, 2, 1000).size
5. No answer returned

So in the 4th step I would like to avoid doing the size check

**Describe the solution you'd like**
Add a boolean parameter to the reader function which indicates if this is the cache/first/final read 

**Describe alternatives you've considered**
The other way I think of doing this is by adding a mutable boolean field to the Store key which is changed/checked in the reader.

**Comment by digitalbuddha** [comment]
Hello! Thank you for using story and opening a enhancement request. Could you tell me the advantage of this boolean over doing the check in your own source of truth impl? My worry is mutable state is going to be something that is hard to get right for the generic case but easy for you to handle in your specific case.

**Comment by digitalbuddha** [comment]
pinging for a response :-) @auras

**Comment by auras** [comment]
I've managed to implement it myself :)

**Comment by digitalbuddha** [comment]
Great! Enjoy your day
