### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#19]
Now that we are getting external contributions, I think it would be beneficial to have some sort of code coverage report in the prs.  @changusmc & @wclausen do you have any thoughts on what we should use?

**Comment by ychescale9** [comment]
Would you also be open to migrating to a more modern assertion library like [truth](https://github.com/google/truth) or [kluent](https://github.com/MarkusAmshove/Kluent)?

**Comment by changusmc** [comment]
> Now that we are getting external contributions, I think it would be beneficial to have some sort of code coverage report in the prs. @changusmc & @wclausen do you have any thoughts on what we should use?

There's two parts to this. (1) Generate the coverage data, for Java and Kotlin, we'd likely have to use Jacoco. I don't know of any other tools that get coverage for Java/Kotlin. (2) Surface the coverage data and enforce coverage on new PRs, some popular tools for this is Coveralls, Codecov, Codacy, all free for open source, but we'll have to get dev-infra to install it for the Dropbox org. That would probably require a software request internally.

**Comment by digitalbuddha** [comment]
@ychescale9 sure! We use truth internally.  I'll make a different issue for tracking

**Comment by wclausen** [comment]
>  some popular tools for this is Coveralls, Codecov, Codacy, all free for open source, but we'll have to get dev-infra to install it for the Dropbox org. That would probably require a software request internally.

I have no strong preference among those. They all seem good/easy to use. I'd go with codecov as their browser extension that shows what lines are covered vs not seems pretty nifty.

**Comment by digitalbuddha** [comment]
Reached out to infra. Let's see what we have available internally

**Comment by burakeregar** [comment]
In the meantime, I will be starting to implement Jacoco. Then we can jump onto the second part when the internal process is done.

> > Now that we are getting external contributions, I think it would be beneficial to have some sort of code coverage report in the prs. @changusmc & @wclausen do you have any thoughts on what we should use?
> 
> There's two parts to this. (1) Generate the coverage data, for Java and Kotlin, we'd likely have to use Jacoco. I don't know of any other tools that get coverage for Java/Kotlin. (2) Surface the coverage data and enforce coverage on new PRs, some popular tools for this is Coveralls, Codecov, Codacy, all free for open source, but we'll have to get dev-infra to install it for the Dropbox org. That would probably require a software request internally.

**Comment by changusmc** [comment]
If you can get the merged coverage.xml and coverage.ec, that would be great
and can support any solution we move forward with. Thanks!
