### ISSUE TITLE
How to get/stream all items of a store?

### ISSUE THREAD

**Issue by NahroTo** [dropbox/Store#193]
It looks like the API is built right now for retrieving singular items only. What if I want to get everything? Using a sealed class Key is what I was suggested, but looking at the source of truth delete(Key) and deleteAll() methods, I assume the Key is clearly meant for keys for single items (such as Int, String etc.) and not as something like Key.All or Key.ById(4).

**Comment by digitalbuddha** [comment]
Hi @NahroTo `deleteAll` was seen as a way to cleanup a store when a session ends/user logs out etc.  Normally I achieve get/stream all items by having 2 stores, one for items and one for the all/collection\

Let's say I have a screen that shows blog posts, I want to be able to show all posts or just 1.
I would then make a 
`PostStore` which takes a key of a postId and return a single item
`AllPostStore` which takes Unit as a key (no key more or less) and returns all items

`PostStore` is the typical get record by ID store, it has a table backing it within a source of truth and a fetcher that retrieves individual items for a key
AllPostStore would be configured with a no memory cache and a source of truth that returns select * from your local storage. It can have a no-op fetcher or a fetcher that gets all items from a network source (still updates same table as PostStore).

The nice part about backing both stores with the same source of truth is that updates from one fetcher (or local writes) will update any streams from either store. Hope that helps!

**Comment by NahroTo** [comment]
I see.

Although the readme suggests that Store represents the Repository pattern, despite the fact the Repository pattern doesnt encourage to use a AllPostsRepository and PostRepository, but just a PostRepository with get and getAll.

What is the difference between using two stores vs using one store with a sealed Key class?

**Comment by NahroTo** [comment]
@digitalbuddha could you comment on the above? One `PostStore` with two Keys, would that be worse?

**Comment by digitalbuddha** [comment]
Store was not designed to have a collection abd single items backed by same store. While it is possible, it is not recommended or well tested. Give it a try and see if it works better for you than chaining stored. Personally I'd have a store per abstraction - one for item, one for list of items

**Comment by NahroTo** [comment]
@digitalbuddha What about if I want to retrieve a `Post` by name? Does it mean I should create a third store named `PostByNameStore`?

**Comment by digitalbuddha** [comment]
If by name identifies individual posts, I would use a sealed class to know whether I pass a name or an ID to the post store

**Comment by NahroTo** [comment]
@digitalbuddha Doesn't that contradict your previous statement? One could argue that getting a post by id is just as a different abstraction as getting a Post by Name, or getting a Post between two dates. Difference between this comparison and the comparison between PostStore and AllPostsStore is that one is a difference in input (`Key`) and the other is a difference output `StoreResponse.Data`
