### ISSUE TITLE
[Question] Testing RxStore

### ISSUE THREAD

**Issue by mezpahlan** [dropbox/Store#196]
Apologies that this is a blank issue but at the moment I don't know if this is a bug / feature request / my misunderstanding.

# Some background

In my project I normally test my RxJava code similar to this:

```
// Given
val classToBeTested = Foo() // A class with functions that return RxJava types

// When
val fooSingleTest = classToBeTested.someSingleReturningFunction().test() // Some function that returns Single<T>

// Then
fooSingleTest.assertValue(...)
```

Which works fine for most of my tests until I get to the ones where I'm (under the covers) using `RxStore`. In those tests I have to do this otherwise the subscription never returns anything nor completes nor errors.

```
// RxStoreBackedRepositoryTest.kt
// Given
val classToBeTested = RxStoreBackedRepository(...) // A class with functions that return RxJava types but under the covers utilises RxStore

// When
val fooSingleTest = classToBeTested.someSingleReturningFunction().test().await() // note the addition of await()

// Then
fooSingleTest.assertValue(...)


-------------------------------------


// RxStoreBackedRepository
class RxStoreBackedRepository(private val api: SomeApi) {

  val repository = StoreBuilder.from<String, String>(
    fetcher = singleValueFetcher {  api.getSomeData(it) }
  )
  .build()

  fun someSingleReturningFunction(request: String) : Single<String> {
    return repository.freshSingle(request)
                     .subscribeOn(Schedulers.io())
  }
}
```

# Question

Maybe it is it my misunderstanding but why do I need to add `await()` to the tests for classes that utilise `RxStore` but not for my other RxJava tests. In both cases the functions return `Single<T>`. I notice that in your tests for [RxSingleStoreExtensionsTest](https://github.com/dropbox/Store/blob/main/store-rx2/src/test/kotlin/com/dropbox/store/rx2/test/RxSingleStoreExtensionsTest.kt) you do the same. I mean it works and my team are happy with it........ I just don't understand why!

I'm using Store4-alpha06 if that helps.

**Comment by digitalbuddha** [comment]
Good question. To be honest I wasn't sure why it was needed. Sounds like we need to investigate it more. I'm on vacation this week, will look next week. Maybe we need to have our own test() extension or a test mode when constructing a store

**Comment by mezpahlan** [comment]
Sounds good. Thanks I'll (a)wait for now. Have a nice holiday.

**Comment by digitalbuddha** [comment]
Hi @mezpahlan I looked at this a bit and I don't think anything out of the ordinary  .  When you call 
```
   store.freshSingle(key)
            .test()
```
store will create a flowable from your source of truth.  In your example, there is no source of truth/ persister created so we will instead use an in memory one.  Next, a "fresh" request is made to your fetcher. The result of which will be written to the source of truth and then read back.  Without something like an await() or a different wait mechanism, the test finishes before the fetcher is hit.  

I think some other singles you are using operating synchronously while store subscribes to a source or truth and waits for data to flow out of it, the single operator is a rxsingle factory around that stream.

```
stream(
    StoreRequest.cached(key, refresh = false)
).filterNot {
    it is StoreResponse.Loading || it is StoreResponse.NoNewData
}.first().requireData()
```

Let me know if that makes sense :-)

**Comment by mezpahlan** [comment]
Hi @digitalbuddha, thanks yes I think it does. 

_Most_ of our other singles are `api.getSomeData()` and our tests trampoline them back to the test thread. When I wrapped this in a `Store` repository the data flow is now asynchronous as you described. I think I was conflating asynchronous with _on a different thread_ and expecting the same behaviour.

So cheers, that does clear it up. :smile_cat:
