### ISSUE TITLE
delete cache module

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#202]
once #200 lands, let's delete the current kotlin cache (sorry @ychescale9 ! it was a great attempt)

**Comment by ychescale9** [comment]
👍 it was a lot of fun writing it.

BTW since we’re deleting it from store, I’m happy to maintain it as a separate repo as I’m using it in a couple of projects at work:)

Or perhaps apollo-android could take over and works on KMP support there? Cc @martinbonnin @tasomaniac

**Comment by digitalbuddha** [comment]
Separate repo sounds great! I'd love to use it as well. Let me double check with legal tomorrow on whether there is a proper way to do this.

**Comment by martinbonnin** [comment]
+1 toi the separate repo where the community could work on building a KMP cache with weigher APIs.

**Comment by tasomaniac** [comment]
To be honest, we can also pull it in Apollo since we are heavily depend on the cache. We can directly work on it to make it available for multiplatform too.

**Comment by martinbonnin** [comment]
Yep, that works too 👍
