### ISSUE TITLE
[Feature Request] Provide a way to warm caches

### ISSUE THREAD

**Issue by inktomi** [dropbox/Store#203]
When we have a particularly important call, it's useful to prefetch the results before we need them. This can be thought of as warming the cache - but there doesn't seem to be an API on Store to do so. 

**Describe the solution you'd like**
It would be nice if we had a `prefetch` call like we have `fresh` - something that just warms the caches. Right now, it seems like the best way to do that is to call `get` but ignore the result? 

**Describe alternatives you've considered**
It's certainly possible to call `get` and ignore the result, but that seems a bit dirty. Also, we don't really _want_ to make the call `get` if the cache is already warm as it would needlessly parse the result and all that.

**Comment by digitalbuddha** [comment]
How would store know if the cache is warm? Also are you talking source of truth or memory cache?

**Comment by digitalbuddha** [comment]
I think get works well for your case as a second get call will return the cached data rather than hitting network. Let me know if I'm missing something. I'm not sure how prefetch impl would differ from get

**Comment by inktomi** [comment]
Yea, `get` does work well enough - and the end result is the same. It seems like Store could have some knowledge about the state of it's internals though - certainly in memory values - so that it knows it doesn't need to go to network or the source of truth. 

Given that logic, then Store should be able to simply return a `boolean` as to if the cache _could_ serve the result already or not without going to network/the source of truth. If not, then we could call `get` (or `prefetch`).

**Comment by digitalbuddha** [comment]
Sounds reasonable. I think this makes sense as a recipe as we can depend on flow operators. To be clear you want a get which forget doesn't return anything?

**Comment by inktomi** [comment]
> To be clear you want a get which forget doesn't return anything?

I think maybe there's a word missing? I'd like a `get` that is fire-and-forget and doesn't return anything, but otherwise acts the same such that it can be used to load things into caches/etc.
