### ISSUE TITLE
Is the documentation for rx2 and rx3 `withScheduler` slightly confusing?

### ISSUE THREAD

**Issue by mezpahlan** [dropbox/Store#207]
Apologies for the blank issue but I'm not sure this is a bug nor is it a feature request at present but I would like to discuss this with you first. Happy to raise a PR if at the end it calls for it.

# Background

I don't know coroutines. Hands up. We're an RxJava app and I've been a bit slow to learn the ins and outs of coroutines. Nevertheless we use Store with the Rx bindings and love it.

# Issue

The documentation for `StoreBuilder::withScheduler` ([rx2](https://github.com/dropbox/Store/blob/main/store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStoreBuilder.kt), [rx3](https://github.com/dropbox/Store/blob/main/store-rx3/src/main/kotlin/com/dropbox/store/rx3/RxStoreBuilder.kt)) says this:

>Define what scheduler fetcher requests will be called on,
>if a scheduler is not set Store will use [GlobalScope]

Now, in my naive RxJava way of thinking I had assumed that this meant if my fetchers would be _executed_ on whichever Scheduler I specify. For example if my fetcher retrieved something from the network like this `api.getSomethingFromNetwork()` it would be executed on the Scheduler in a way that is equivalent to `api.getSomethingFromNetwork().subscribeOn(...)`.

In other words if you had this before you integrated Store:

```
api.getSomethingFromNetwork()
   .subscribeOn(Schedulers.io())
```

I had assumed the following would be equivalent:

```
StoreBuilder.from<Int, String>( fetcher = Fetcher.ofSingle { api.getSomethingFromNetwork() } )
            .withScheduler(Schedulers.io())
            .build()
```

But now we have the benefit of Store's default memory caching policy.

However when I looked closer at the documentation and source I started to get a little confused. `withScheduler` points to [`StoreBuilder::scope`](https://github.com/dropbox/Store/blob/main/store/src/main/java/com/dropbox/android/external/store4/StoreBuilder.kt) which is documented as:

>A store multicasts same [Output] value to many consumers (Similar to RxJava.share()), by default
>[Store] will open a global scope for management of shared responses, if instead you'd like to control
>the scope that sharing/multicasting happens in you can pass a [scope]

I understand RxJava's [`share()`](http://reactivex.io/RxJava/javadoc/rx/Observable.html#share) and it makes sense to me the reference in the documentation of `scope` as to why it is referring to multicasting the output. I think of the same in RxJava terms as multicasting the _emissions_. However, I don't quite get the documentation of the Rx bindings given this. To me _requests called on_ is not the same as how the emissions are multicast after the request has been concluded.

# Suggestions

1. Tell me to naff off because what's there is correct and I have misunderstood. :smile_cat: 
2. If my rambles do make sense to you then would an appropriate change be:

>Define what scheduler fetcher requests will be multicast on,
>if a scheduler is not set Store will use [GlobalScope]. 

Again, happy to raise a PR if you agree.

**Comment by digitalbuddha** [comment]
Hello! This seems to be a case of the comment not at all aligning with the implementation. Apologies for that. The scheduler is actually used for backing the multicaster as you noticed. Let me touch base with folks about intent of the implementation and post back. At worst we'll update the doc.

**Comment by digitalbuddha** [comment]
sorry for delay, diff is up
