### ISSUE TITLE
Failed to resolve: com.dropbox.mobile.store:store4:4.0.0-alpha07

### ISSUE THREAD

**Issue by NahroTo** [dropbox/Store#215]
Looks like v4.0.0-alpha07 is not accessible through gradle yet.
EDIT: https://search.maven.org/artifact/com.dropbox.mobile.store/store4/4.0.0-alpha06/jar

**Comment by nikedlab** [comment]
Yep. Maven repository contained only alpha06 on the top

**Comment by digitalbuddha** [comment]
working on it, had a few release issues :-) hang tight

**Comment by NahroTo** [comment]
@digitalbuddha Any ETA?

**Comment by digitalbuddha** [comment]
We pushed it up, will propagate in few hrs
