### ISSUE TITLE
[BUG] duplicate classes issue after add store dependency that hasn't solved after excluding duplicate dependencies

### ISSUE THREAD

**Issue by Gelassen** [dropbox/Store#221]
**Describe the bug**
I have a project boosted by bunch of common dependencies. After adding a store (`implementation 'com.dropbox.mobile.store:store4:4.0.0-alpha07'`) I can't build the app with error: 

`Duplicate class kotlinx.coroutines.AbstractCoroutine found in modules kotlinx-coroutines-core-1.3.4.jar (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.4) and kotlinx-coroutines-core-jvm-1.3.9.jar (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9)
`

Here is dependency tree ((*) or () indicates duplicate libs): 

> +--- com.dropbox.mobile.store:store4:4.0.0-alpha07
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.0 (*)
|    +--- com.dropbox.mobile.store:cache4:4.0.0-alpha07
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0 (*)
|    +--- com.dropbox.mobile.store:multicast:4.0.0-alpha07
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9 (*)

and here is an attempt to remove duplicates: 

>     implementation('com.dropbox.mobile.store:store4:4.0.0-alpha07') {
>         exclude group: 'org.jetbrains.kotlinx', module: 'kotlinx-coroutines-core'
>         exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
>         exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
>         exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
>         exclude group: 'org.jetbrains.kotlinx', module: 'kotlinx-coroutines-core-jvm'
>     }

but after launch the app crashes and reports variety of `NoSuchMethodError` 

I plan to try this lib from scratch next week and isolate the issue, but had a thought it may be worth to share it with you. 

**To Reproduce**
1. Check the app https://github.com/Gelassen/government-rus or use dependencies from it in new project (deps.gradle and app/build.gradle)
2. Add dropbox/store `implementation 'com.dropbox.mobile.store:store4:4.0.0-alpha07'`
3. Run the app

**Expected behavior**
App runs without crash

**Smartphone:**
 - Device: Nexus 5
 - OS: Android 6

**Comment by Gelassen** [comment]
Thanks, it resolved issue.

**Comment by AymenJeghamPro** [comment]
> Updating all of your project's coroutine dependencies to 1.3.9 solved this for me.

didn't work for me

**Comment by animesh-sharama** [comment]
@NahroTo How to update the entire project coroutine dependency to  1.3.9?
