### ISSUE TITLE
[needs-info] samples how to use dropbox/store with Retrofit Flow

### ISSUE THREAD

**Issue by Gelassen** [dropbox/Store#222]
Is there any samples of dropbox store usage? 

In general info from readme on the project's main page is good, but it would be better to have code to run and check. Being more specific I have an issue with running dropbox/store with Retrofit api that returns result as a Flow. 

I already discovered you have an option to run as nonFlow and I am going to explore it more (most/all samples I saw used it), however I still interested to use Flow as a response from retrofit client with dropbox utils. 

The issue in the demand of custom call adapter:

`IllegalArgumentException: Could not locate call adapter for kotlinx.coroutines.flow.Flow<Response<Data>> `

Likely it is possible to implement it, but it would take time to go deeper under high level abstractions and would be good to check around what community already shares with world. 

[Excuse me if this question looks as a not appropriate. Android is evolving quite rapid, seems if you switch stacks instead of commit all your time on Android projects you have to quickly learn many recently introduced things and force you use all avaiable options to cut the time ]

**Comment by Gelassen** [comment]
**Actually the lastest Store API doesn't have StoreBuilder.fromNonFlow option**

**Comment by digitalbuddha** [comment]
Hello! Flow is a type that is used for a stream of values. Retrofit is normally used for single shot responses. By default retrofit does not have a flow adapter.

Your options are to use `suspend` fun which has support in retrofit or to implement/find a retrofit flow adapter
