### ISSUE TITLE
[Question] How to detect that data was removed from SourceOfTruth?

### ISSUE THREAD

**Issue by aartikov** [dropbox/Store#224]
Hi.
Store emits `StoreResponse.Data` whenever data in `SourceOfTruth` is modified, but it emits nothing when data was removed. I want to have my UI in sync with the stored data, i.e to show empty view when there are no data. What is the best way to implement it?

**Comment by aartikov** [comment]
@eyalgu Could you please help with the question?

**Comment by aartikov** [comment]
@digitalbuddha Could you please help with the question?

**Comment by digitalbuddha** [comment]
I don't think we have considered a removal case. One way to handle is by having a custom result type and rather than returning data from your source of truth return a result for data or removals.

**Comment by aartikov** [comment]
@digitalbuddha 
Does it make sense to add `StoreResponse.DataRemoved`?

**Comment by digitalbuddha** [comment]
Since we delegate to user's SourceOfTruth this can be implemented within a SourceOfTruth. Closing as I don't think this is generic enough to be a library feature
