### ISSUE TITLE
[Question] Where does store land in Clean Architecture layers?

### ISSUE THREAD

**Issue by halilozercan** [dropbox/Store#236]
Clean Architecture has a pretty clear definition of repository pattern and its implementation. Domain layer holds the interface of Repositories defining business logic while data layer provides a default implementation for repositories using network and database calls (e.g. retrofit and room). However, my understanding is that domain layer should have as few dependencies as possible to 3rd party libraries. 

Until now, I felt comfortable introducing RxJava or Flow into domain repositories as return types. With Store, I'm not really sure what to return from repository calls; Store or Stream?

My current approach is that repository returns Store instances for each call e.g., 
```
fun comments(): Store<CommentsRequest, CommentsResponse>
```
Later, I initialize and return the store in data layer implementation of this interface. 

Finally, in UI Layer I use something like UIController which wraps around a Store and Refresh request. Is there another alternative that suits better to Clean Architecture?

**Comment by digitalbuddha** [comment]
Generally I have been using store as a building block for a repository. By that I mean I create a repository which has a store as an internal implementation. I treat stores as a service rather than something that gets returned.

**Comment by halilozercan** [comment]
Do I need to reuse the same store instance to benefit from in-memory caching?

**Comment by digitalbuddha** [comment]
Yes. Currently the memory cache is internal to a store. You'd have to use the same instance to get shared caching. You are however able to share the same source of truth implementation between many stores. Think of a store as a wrapper for a network and local data storage call. If updates are not needed in my repository I sometimes use the store as the repository. If I do need updates I then have a repository that can  update the backing database that Store's reader is connected to.

Hope that helps.
