### ISSUE TITLE
Why does Store.observe use stream(request).asFlowable() instead of rxFlowable { stream(request) }?

### ISSUE THREAD

**Issue by mezpahlan** [dropbox/Store#237]
Apologies for the blank issue again, but I wanted to discuss this first before presupposing if this is a feature or a bug.

All extensions in [RxStore](https://github.com/dropbox/Store/blob/main/store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStore.kt) appear to use functions in the form `rxSingle { }` or `rxCompletable { }` apart from `Store.observe` which uses `...asFlowable()`.

```
Store.observe(request: StoreRequest): Flowable = stream(request).asFlowable()
```

Is there a reason for this or could it use this instead?

```
Store.observe(request: StoreRequest): Flowable = rxFlowable { stream(request) }
```
Shortened for brevity.

This isn't high priority or anything, just something I was curious about. The intricacies in the internals of `asFlowable()` and `rxFlowable { }` are lost on me :cry: .

**Comment by digitalbuddha** [comment]
I don't think it was intentional. When we wrote the bindings I think we went with whatever we saw in the kotlin docs. Is there a behavioral difference or just curious?

**Comment by mezpahlan** [comment]
Just curiosity.
