### ISSUE TITLE
[Feature Request] Flowable helper factories for `get` and `fresh`

### ISSUE THREAD

**Issue by mezpahlan** [dropbox/Store#238]
**Is your feature request related to a problem? Please describe.**
I'm trying to follow a similar pattern to our usage of `Store.getSingle` and `Store.getFresh` but with `Flowable<Output>` as the return type. I want our reactive database to be updated and then (through Store) our UI to benefit. Does it make sense to even offer that factory in the context of a Flowable? I can't think of a reason not to, but I'm happy to be told it is not a good idea.

**Describe the solution you'd like**
Helper factories in both the `rx2` and `rx3` extension modules that look like this:

```
/**
 * Helper factory that will return stream of data as a [Flowable] for [key] if it is cached otherwise will return fresh/network data (updating your caches)
 */
fun <Key : Any, Output : Any> Store<Key, Output>.getFlowable(key: Key) = rxFlowable { this@fgetFlowable.foo(key) }

/**
 * Helper factory that will return a fresh stream of data as a [Flowable] for [key] while updating your caches
 */
fun <Key : Any, Output : Any> Store<Key, Output>.freshFlowable(key: Key) = rxFlowable { this@freshFlowable.bar(key) }
```

Note: I've not thought about how to define `foo` or `bar` from the `store4` module which would need to return a `Flow<Output>` but _could_ look something like this:

```
Store.foo(key: Key): Flow<Output> = stream(StoreRequest.cached(key, refresh = false))
                                     .filterNot { it is StoreResponse.Loading || it is StoreResponse.NoNewData }
                                     .map { it.requireData }

Store.bar(key: Key): Flow<Output> = stream(StoreRequest.fresh(key))
                                     .filterNot { it is StoreResponse.Loading || it is StoreResponse.NoNewData }
                                     .map { it.requireData }
```

**Describe alternatives you've considered**
Writing the above as local extension functions in our code base.

**Additional context**
I'm happy to raise a PR if you think this is worth pursuing.

**Comment by digitalbuddha** [comment]
sorry I don't quite understand if this is different from https://github.com/dropbox/Store/blob/main/store-rx2/src/main/kotlin/com/dropbox/store/rx2/RxStore.kt#L22

**Comment by mezpahlan** [comment]
Hi there. I think because that extension function returns `Flowable<StoreResponse<Output>>` whereas this would return `Flowable<Output>`.

I suppose to further elaborate on where my thinking is I'm looking to use Store with the following types:

1. Single<Output> <-- I can do this right now with the extensions in store-rx2(3) which apply over the helper extensions in store.
2. Maybe<Output> <-- I can do this right right with RxJava operators on top of 1.
3. Flowable<Output> <-- I'd like to also do this.

**Comment by digitalbuddha** [comment]
Makes sense! Sure we'd gladly accept a pr. Thanks for explaining
