### ISSUE TITLE
[Question] How to update cache by another api

### ISSUE THREAD

**Issue by hvsimon** [dropbox/Store#239]
Assuming there are two api: `getPoints()` and `updatePoints()`.

The `getPoints()` would respond latest points from server.
The `updatePoints()` would update points and respond latest points from server.

I build a store:
```
val pointStore = StoreBuilder.from<Unit, Int>(
    Fetcher.of { api.getPoints() }
).build()
```

And get the points by
```
pointStore.get(Unit)
```

But how to update data in `pointStore` when I called `api.updatePoints()`?
Instead of calling `api.getPoints()` again.

**Comment by digitalbuddha** [comment]
Hello! you would need to use something that allows updating. Take a look at our sample project where we use Room. You would then be able to update the room records and the store will emit again
https://github.com/dropbox/Store/blob/main/app/src/main/java/com/dropbox/android/sample/data/model/DbModel.kt

Currentlly store does not have an update api but instead respects a local source of truth that can be updated
