### ISSUE TITLE
store.stream(StoreRequest.cached(key = key, refresh = false)) does not call the Fetcher when source of truth is empty 

### ISSUE THREAD

**Issue by mamadou94Diop** [dropbox/Store#241]
**Describe the bug**
When I use `store.stream(StoreRequest.cached(key = key, refresh = false))`, Store tries first to get data from **source of truth** and does not call **Fetcher** when source of truth is empty.

Putting **refresh** at **true** does call **Fetcher** when **source of truth** is empty but that Fetcher will be called at every query, implying to break the objective of reducing network calls I wanted to achieve.

**To Reproduce**
1. Implement a Store with a **source of truth** and **Fetcher** : 
2. Use the store with following code : `store.stream(StoreRequest.cached(key = key, refresh = false))` 
3. Using log debug to find the origin of data in `collect` callback
4. Figuring out that only source of truth is called 

**Expected behavior**
I would like it behaves as described in your blog article : [https://dropbox.tech/mobile/store-grand-re-opening-loading-android-data-with-coroutines](https://dropbox.tech/mobile/store-grand-re-opening-loading-android-data-with-coroutines), with the workflow described here: 

- Fetch on source of truth
- if source of truth is empty call Fetcher
- Fill cache and source of truth with Fetcher result
- Finally Rely on cache or source of truth data

![store cached](https://user-images.githubusercontent.com/56298253/97078793-db440580-15ee-11eb-9c1e-acc9903fe4a6.gif)

**Screenshots**
![Capture d’écran 2020-10-24 à 12 12 16](https://user-images.githubusercontent.com/56298253/97079197-34f9ff00-15f2-11eb-8f8d-ee6740556309.png)

**Smartphone (please complete the following information):**
 - Device: Nexus S (Emulator)
 - OS:  Android 10
 - Store Version  4.0.0-beta01

**Additional context**
I try to get a catalog of burgers, Store would fit to my needs by fetching api and feeding source of truth that I would use for next calls.

**Comment by eyalgu** [comment]
From the screenshot it seems like your source of truth is returning an empty catalog to Store. As far as Store is concerned that is a valid object that is returned to you from the SoT and thus no fetch is required. 

If you want to trigger a fetch in the case of an empty dialog return `null` instead of valid object.

**Comment by mamadou94Diop** [comment]
Hello @eyalgu, I tried to return a list of burgers with that code :
```
@Query("SELECT * FROM burger")
fun get(): Flow<List<LocalBurger>?>
```
My return type is `Flow<List<LocalBurger>?>` which is supposed to return null given that I put an optional but according to Android documentation(cf :[https://developer.android.com/reference/androidx/room/Query]( https://developer.android.com/reference/androidx/room/Query)) :

> 

- When the return type is Flow<T>, querying an empty table throws a null pointer exception.

- When the return type is Flow<T?>, querying an empty table emits a null value.

- When the return type is Flow<List<T>>, querying an empty table emits an empty list.

Eventhough my list is an optional, Room always returns an empty list when I called **get** function implying not calling the **Fetcher** .
To confirm that hypothesis, I changed **get** function from dao signature, to fetch now only one row : 
```
 @Query("SELECT * FROM burger")
 fun get(): Flow<LocalBurger?>
```
In addition of that, I changed the store signature from `Store<String,List<LocalBurger>>` to `Store<String, LocalBurger>`, finally the fetcher was called and the single row queried is displayed in my UI.

I will ask on room github repo for a solution allowing to return null when the method signature in type of `Flow<List<T>?>`  returns empty rows.
