### ISSUE TITLE
[Question] is this erratic behaviour or does it work as intended?

### ISSUE THREAD

**Issue by edualonso** [dropbox/Store#243]
Hi Store folks.

I'm a member of the Android Realm DB team. I am currently working on updating some really old examples we have in our codebase. We have been following your library for a while and we have decided to explore it now that it runs full-steam on coroutines. We are simultaneously working on some coroutines extensions for our Java SDK, so this assignment serves us to validate (or not) our approach in a real-world scenario. So far we are quite pleased with the simplicity of the Store API and look forward to using it to showcase how to use the repository pattering using coroutines.

As I've been writing the code for our example, I've encountered a few behaviours I can't really explain. The use case I'm working on is a simple news reader app, which has a drop-down spinner from which users can select a section, e.g. politics, technology, arts, etc. and then a list showing some news headlines will reflect the contents of that particular section.

The first load with a default "home" section works just fine and the list gets updated correctly. However, things don't quite work once we select a different section than the default one. Our `NewsReaderViewModel` looks roughly like this:

```
var section: String = "home"

init {
    val fetcher: Fetcher<String, List<NYTimesArticle>> = Fetcher.of { apiSection ->
        // suspend fun getTopStories(section: String): NYTimesResponse
        nytApiClient.getTopStories(apiSection).results
    }

    val sourceOfTruth: SourceOfTruth<String, List<NYTimesArticle>, List<RealmNYTimesArticle>> = SourceOfTruth.of(
            reader = { apiSection ->
                // fun getArticles(section: String): Flow<List<RealmNYTimesArticle>>
                realmDao.getArticles(apiSection)
            },
            writer = { apiSection, articles ->
                // suspend fun RealmNYTDao.insertArticles(apiSection: String, articles: List<NYTimesArticle>)
                realmDao.insertArticles(apiSection, articles)
            },
            delete = { apiSection ->
                // suspend fun deleteArticles(section: String)
                realmDao.deleteArticles(apiSection)
            },
            deleteAll = {
                // suspend fun deleteAllArticles()
                realmDao.deleteAllArticles()
            }
    )

    store = StoreBuilder.from(fetcher, sourceOfTruth)
            .build()

    setupStoreStream()
}

private fun setupStoreStream() {
    store.stream(StoreRequest.cached(
            key = section,
            refresh = true
    )).onEach { response ->
        val origin = response.origin.toString()

        when (response) {
            is StoreResponse.Loading -> NewsReaderState.Loading(origin)
            is StoreResponse.Data -> NewsReaderState.Data(origin, response.value)
            is StoreResponse.NoNewData -> NewsReaderState.NoNewData(origin)
            is StoreResponse.Error.Exception -> NewsReaderState.ErrorException(origin, response.error)
            is StoreResponse.Error.Message -> NewsReaderState.ErrorMessage(origin, response.message)
        }.let {
        // Update livedata property to notify fragment and update list
            _newsReaderState.postValue(it)
        }
    }.launchIn(viewModelScope)
}

fun getTopStories(apiSection: String) {
    viewModelScope.launch {
        section = apiSection
        store.fresh(section)
    }
}
```

I haven't added any caching policy and I'm always getting fresh data to keep it simple.

Once we call `getTopStories` with a new section, say "arts", the execution stream goes as follows:

1. fetcher: gets news from API and delivers "news API objects"
2. writer: uses Realm DAO to map "news API objects" to "Realm news objects" and saves them in the database
3. stream: receives a `StoreResponse.Data` with origin `SourceOfTruth` with a list of "Realm news objects" containing items matching the **original "home" section**, which is used to update a `LiveData` property which will in turn update the list
4. reader: launches a query with the new `section` and returns a `Flow<List<RealmNYTimesArticle>>` - after debugging this step I can confirm the database contains the newly added items corresponding to the newly selected "arts" section, however, this flow never gets the items emitted
5. no more stream callbacks are received after 4

I'm a bit puzzled as to why this is happening. Perhaps I haven't understood something along the way regarding how the library works, but it seems something is going on. I would be really grateful if you guys could give me an explanation as to why I'm experiencing this. I could also provide a link to our repository so that you can experiment with the example first-hand.

Thanks in advance!

**Comment by digitalbuddha** [comment]
From first glance the thing I see as unideal is using a mutable field for the stream key and then reusing it again for the fresh call. Do you have a sample to share? First I'd recommend making keys immutable and trying again. This looks close to our sample app, if you can't share your code, could you make our sample fail in same way? Thank you and hope that helps

**Comment by digitalbuddha** [comment]
Also you mention in 4 the flow never gets emitted. Is that the Database flow or the store stream flow? Wanted to confirm that indeed the flow from realm is emitting when something is written

**Comment by edualonso** [comment]
> Also you mention in 4 the flow never gets emitted. Is that the Database flow or the store stream flow? Wanted to confirm that indeed the flow from realm is emitting when something is written

I've tried three approaches:

- First I used our `toFlow` method. The Realm flow is closed before having the Store stream emit anything. We have implemented it using `callbackFlow` and what happens is that the `awaitClose` block we use to keep it alive is called before the Realm change listener that should offer the newly inserted results kicks in. We were not fully sure our implementation was bulletproof so we revisited it and found two minor things after receiving feedback from some users. These things are more related to unclear semantics from our side though, so it wasn't an indication on why this could be happening. In any case, the implementation is similar to that of our RxJava convenience method `asFlowable`.
- Then I decided to use `asFlowable` as the database publisher and have `asFlow` from `kotlinx-coroutines-rx2` piggyback on it to convert the output to a Kotlin flow. The problem here seems to be similar, with the difference that our `asFlowable` implementation manages to emit the newly inserted elements only to be disposed immediately afterwards and not emitting anything upwards towards the Store stream.
- Finally I implemented the same thing using Room and have my DAO return a flow to sanity-check the problem isn't in our implementation. After debugging the generated Room DAO I can see the behaviour is similar to my second attempt using flowable mapped to flow. The DAO flow emits something when the reader is executed in step 4, but it never is emitted and propagates to the Store stream.

If you need more information or further details, please let me know. I could provide a detailed debugging explanation if needed.

> First I'd recommend making keys immutable and trying again.
Making the key immutable didn't help. Having it like that was only a primitive/draft attempt to save the view state in case of configuration changes. We will surely not rely on that property and use the drop-down spinner internal state instead, which is saved upon rotation so it shouldn't be a problem in this case.

> Do you have a sample to share?
Absolutely. I can have it ready at some point tomorrow. I'll post a link here.

**Comment by edualonso** [comment]
@digitalbuddha the sample project can be found here: https://github.com/realm/realm-java/tree/el/store-coroutines-example/examples/coroutinesExample

**Comment by digitalbuddha** [comment]
Perfect thank you! I'll have time to look over the weekend

**Comment by eyalgu** [comment]
Hi @edualonso - From I believe the problem is that you're trying to reuse the same `Store.steam` for different keys (sections), that's just not going to work. 

Once you set up the `Store.Request` the `section` key is copied over as the key and will not change. The stream will only emit new result for the original key. To fix your example, you'll need to cancel the old stream collection job and start a new one.

You probably need something like:
```
var section: String = "home"
private var currentJob: Job? = null

init { ... }

private fun setupStoreStream() {
    **currentJob?.cancelAndJoin()
    currentJob =** store.stream(StoreRequest.cached(
            key = section,
            refresh = true
    )).onEach { response ->
        val origin = response.origin.toString()

        when (response) {
            ...
        }.let {
        // Update livedata property to notify fragment and update list
            _newsReaderState.postValue(it)
        }
    }.launchIn(viewModelScope)
}

fun getTopStories(apiSection: String) {
    viewModelScope.launch {
        section = apiSection
        **setupStoreStream()**
    }
}
```

As an aside note, the reason you're getting a new emission on the stream after calling `fresh` is probably because `fresh` updates the underlying table managed by realm which causes realm to emit on all the flows listening to the table, regardless of whether their individual results have changed.

**Comment by eyalgu** [comment]
Since this may end up informing documentation there's an unrelated small issue that's worth highlighting here:
```
reader = { apiSection ->
                // fun getArticles(section: String): Flow<List<RealmNYTimesArticle>>
                realmDao.getArticles(apiSection)
            }
```
since `getArticles` returns a Flow<List<_>> it will, when there's no result in the database, return an empty list. as far as store is concerned an empty list != no results so `store` will initially return an `StoreResponse.Data(emptyList(), ResponseOrigin.SourceOfTruth)` and only then start the fetcher.

For the sample I would fix this by updating the reader to be something like:

```
reader = { apiSection ->
                // fun getArticles(section: String): Flow<List<RealmNYTimesArticle>>
                realmDao.getArticles(apiSection).map { if (it.isEmpty()) null else this }
            }
```

**Comment by edualonso** [comment]
I thought the same stream would emit all updates irrespective of the key. That explains it. Thanks a lot for the clarification.
