### ISSUE TITLE
[BUG] No way to retrieve only cached value

### ISSUE THREAD

**Issue by chrisbanes** [dropbox/Store#245]
See https://github.com/dropbox/Store/issues/245#issuecomment-732159832

**Comment by digitalbuddha** [comment]
Refresh true would give a double tap. Ie even if data exists on disk it will still hit fetcher. Get with refresh false should return first available source. Are you seeing different?

**Comment by chrisbanes** [comment]
Hmmm, I haven't actually tried it since I have my own extension functions.

Is there a way to retrieve _only_ the cached version? i.e. no fetcher at all. The reason I found this was because I have a `cachedOnly()` ext-fun which is implemented exactly the same. Obviously I mis-read the contract.

**Comment by digitalbuddha** [comment]
I don't believe we expose cache only. Could you give me more insight into the use case?

**Comment by chrisbanes** [comment]
Probably best explained by my extension funs:

``` kotlin
suspend fun <Key : Any, Output : Any> Store<Key, Output>.fetch(
    key: Key,
    forceFresh: Boolean = false,
    doFreshIf: suspend (Output) -> Boolean
): Output = when {
    // If we're forcing a fresh fetch, do it now
    forceFresh -> fresh(key)
    else -> {
        // Else we'll check the current cached value
        val cached = cachedOnly(key)
        if (cached == null || doFreshIf(cached)) {
            // Our cached value isn't valid, do a fresh fetch
            fresh(key)
        } else {
            // We have a current cached value
            cached
        }
    }
}

suspend inline fun <Key : Any, Output : Any> Store<Key, Output>.cachedOnly(key: Key): Output? {
    return stream(StoreRequest.cached(key, refresh = false))
        .filterNot { it is StoreResponse.Loading || it is StoreResponse.NoNewData }
        .first()
        .dataOrNull()
}
```

Example usage:
```
showStore.fetch(params.showId) {
    // Refresh if our cached data is over 14 days old
    lastRequestStore.isRequestExpired(params.showId, Period.ofDays(14))
}
```

It allows the caller to specify when/if to fetch. I could bake this into the fetcher, but then I have no way to override and force a fetch.

**Comment by digitalbuddha** [comment]
Got it. Sounds like you want to get cached value, if it is invalid then get fresh. That to me feels like a stale policy on the source of truth/cache. Any reason not to have your cache/source of truth only return if it is a valid cache entry? This way you can handle within your own source of truth impl. 

In store3 we had a an override for record policy for the source of truth, maybe it's time to do that again. General api would be that the record policy call needs a valid response to then read from the source of truth

**Comment by OrhanTozan** [comment]
@chrisbanes Maybe I'm missing something, but isn't your cachedOnly extension method the same as the existing Store.get() extension?:
```
/**
 * Helper factory that will return data for [key] if it is cached otherwise will return
 * fresh/network data (updating your caches)
 */
suspend fun <Key : Any, Output : Any> Store<Key, Output>.get(key: Key) = stream(
    StoreRequest.cached(key, refresh = false)
).filterNot {
    it is StoreResponse.Loading || it is StoreResponse.NoNewData
}.first().requireData()
```

**Comment by OrhanTozan** [comment]
@digitalbuddha 

> Got it. Sounds like you want to get cached value, if it is invalid then get fresh.

Isn't  this what Store.get() already does?

**Comment by chrisbanes** [comment]
> isn't your cachedOnly extension method the same as the existing Store.get() extension?
Yes, which is what prompted this bug.

> Isn't this what Store.get() already does?
Yes, but Store currently decides what is valid/invalid. I want to control that myself.

**Comment by chrisbanes** [comment]
> Any reason not to have your cache/source of truth only return if it is a valid cache entry? This way you can handle within your own source of truth impl.

I could do this, but I then have no way to override the behavior and force a fresh fetch. My primary use-case is: when a screen is displayed, do an optional refresh from the ViewModel. If the user presses refresh, force a fresh fetch. I see no way to do that from the SourceOfTruth/fetcher since I can't pass through any parameters from the original call.

// EDIT: I think this will actually work for me. Trying now.

**Comment by chrisbanes** [comment]
Closing this as the re-worked SourceOfTruth seems to be working nicely 👍
