### ISSUE TITLE
[QUESTION] Multiple stores to query same entity in different forms with same memory cache

### ISSUE THREAD

**Issue by lordcodes** [dropbox/Store#262]
This may be me trying to use Store in a manner it wasn't designed.

Say, I have a Blog Post entity, which depending on the screen I want to obtain via:

* Single post via it's ID
* All posts
* A list of posts with the same tag
* A list of posts via a list of IDs

These would all be using the same Source of Truth DAO, but each using different queries to obtain the list of posts, with the top one only returning either a single result or null. Each of the stores has a fetcher to obtain the relevant posts as well.

Obviously you could just turn off memory caching, but I was hoping to share a memory cache containing the last X posts requested through any of the stores.

This would mean on a screen that displays say the list of posts for a tag they would get cached in memory, then when opening the next screen that displays a single post via ID it would already be in that memory cache.

Now it may be the memory cache was only really designed to handle screen rotation, i.e. sequential access to same entity, but I was wondering if I had missed something when looking at the API to try and achieve the above.

**Comment by yigit** [comment]
Store caches are key based so it wont' be able to handle this out of the box.
What you can try to do is to make one store source of another store such that it queries the other one with cached before going to network. You'll still be duplicating the in memory cache though.

Alternatively, you can make it such that you have a store for posts with queries by id and other stores that only keep list of ids in memory and piggyback on the post store for values.

**Comment by lordcodes** [comment]
Thank you very much, really useful. Will look into the options you mentioned.
