### ISSUE TITLE
Multicast could have a keep-alive mode

### ISSUE THREAD

**Issue by yigit** [dropbox/Store#27]
Right now, multicast kills the upstream if there are 0 consumers.

It  would be nice if it had a mode where it kept the upstream alive as long as the given scope is alive, even if there are no consumers. Alternatively, it could have a delay for killing upstream to achieve this.

This is something we needed in paging. Basically, during rotation, consumer count goes to 0 which means the upstream paging flow will be closed, requiring the new activity to restart it from scratch.
That is waste of work, especially there are intermediate transformations.

There is a hacky workaround where it can keep a collector active in the `viewModelScope` but that would make the upstream hot.
The desired behavior is to just not cancel it and upstream will eventually suspend as no values will be consumed.

**Comment by digitalbuddha** [comment]
Isn't what you are describing basically making it hot? At what point will the producer be cancelled if it is alive past last subscriber? Do you really want it hot or do you want to cache the value? 

My initial reaction is that I think this is more a use case for just using Store and called store.get in both situations, the first time you'll make the flow and the second time you won't get past the caches. 

Another approach - you mention issue is expensive transformations, would a distinctUntilChanged work somewhere? Basically don't emit the producer value a second time if the same?

Btw store3 had store.stream that was a hot channel that the store maintained and future get calls side effect to so maybe there is something with this need.

**Comment by yigit** [comment]
This does not make producer hot.
It will still be suspended when it tries to emit a value since there are no downstream consumers to `ack` the value.

This is not about distinct until changed. It is about restarting an upstream flow when we don't want to. Paging dispatches a stream of events that needs to be fully consumed to create the paged data. These events can have transformations (possibly expensive). The desired behavior is to cache transformed values in the view model and re-connect any new activity (or any new subscriber) and utilize multicast cache to re-dispatch all events that already had their transformations applied.

**Comment by digitalbuddha** [comment]
Ah makes sense I misunderstood. Sounds good to me!

**Comment by eyalgu** [comment]
#29 should make adding this functionality easier

**Comment by yigit** [comment]
i've started tinkering w/ this.
I think the best way to implement is actually on top of Multiplexer (like an operation on it) where it can keep a consumer alive that does not ack the incoming messages.

playing w/ this now, API is a bit tricky but hopefully will have something soon as a WIP.

**Comment by eyalgu** [comment]
I'm probably missing something, but why isn't it enough to change `ChannelManager.doRemove` to check a flag and not `cancelAndJoin` the producer if in keepalive mode?

**Comment by eyalgu** [comment]
e.g bbf0620a90944380b694890359f233c988cf5bf9

**Comment by yigit** [comment]
hmm might be enough as long as there is non-zero buffer. If buffer is zero, then any following upstream value will not be ack'ed.

**Comment by eyalgu** [comment]
buffer fix: c14aed709b62e4c6b7b0354efa6f26e3600af29b. I can make it into a PR once the actor PR is merged

**Comment by digitalbuddha** [comment]
Yes pls

**Comment by eyalgu** [comment]
#40 is up
