### ISSUE TITLE
[BUG] No static method toDuration MemoryPolicy

### ISSUE THREAD

**Issue by rosebm** [dropbox/Store#276]
**Describe the bug**
The app is crashing with this error since today (I thought it was one of my changes, but tested on a unaltered branch and  is occurring also): 

```
    java.lang.NoSuchMethodError: No static method toDuration(DLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in  /data/app/com.....
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:116)
```

Thought about removing the cachePolicy from the StoreBuilder, nevertheless, with that approach I'm getting:

```
java.lang.NoSuchMethodError: No static method toDuration(ILjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.....
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:16)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
```

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 9
 - Store Version: 4.0.1
 - Kotlin: 1.4.32

**Comment by digitalbuddha** [comment]
Please use this version instead. There were some breaking changes to duration api. https://search.maven.org/artifact/com.dropbox.mobile.store/store4/4.0.2-KT15/jar

**Comment by es0329** [comment]
Hi @digitalbuddha. I'm seeing this crash trace with `Store 4.0.2-KT15` and `Kotlin 1.5.31`.

Was there a directive I might've missed or shall I create another issue for it?

**Comment by digitalbuddha** [comment]
Could you try 4.0.4-KT15 and apologies for the bad naming of versions

**Comment by es0329** [comment]
That version works. Thanks @digitalbuddha!
