### ISSUE TITLE
Migrate file system persister to work with store4

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#34]
Migrating to  Store4 did not migrate the file system module and file system persister to work with the coroutine store4.  This issue is to take the file system persister and make it work with source of truth abstraction

**Comment by pavlospt** [comment]
I can take a look at it! Should I look the Room persister for general direction?

**Comment by digitalbuddha** [comment]
Take a look at store builder and source of truth. That is the interface that was the old "persister"

**Comment by digitalbuddha** [comment]
A good first step is to get https://github.com/dropbox/Store/blob/master/filesystem/src/main/java/com/dropbox/android/external/fs3/FileSystemPersister.kt to integrate with `StoreBuilder`

**Comment by pavlospt** [comment]
@digitalbuddha thank you for the tip! I was checking the codebase yesterday, kind of getting my mind around the new design :) Will try to integrate that today!

**Comment by pavlospt** [comment]
I am afraid, I won't be able to take up on this task, due to time constraints + new job 😞 Sorry for that, the issue is up for grabs again!

**Comment by digitalbuddha** [comment]
Fixed during #56
