### ISSUE TITLE
[BUG] I get only Loading response, nothing after that

### ISSUE THREAD

**Issue by kosiarska** [dropbox/Store#349]
**Describe the bug**
I use Timber.e to log a response from collect call. I get only Loading(origin=Fetcher) and nothing after that. Data is persisted into room (I checked this in app inspection in android studio).

**To Reproduce**
load Method, "info_uj" is the parameter of retrofit call

<img width="883" alt="Zrzut ekranu 2021-11-20 o 19 49 06" src="https://user-images.githubusercontent.com/4482239/142737780-22011474-e4fe-4a34-acd2-59d63b4de2fd.png">

retrofit call looks like this:
` @GET("api/directories/{id}")
    suspend fun getDirectoryById2(@Path("id") id: String): SingleDirectoryResponse
`

**Expected behavior**
After loading there should be callback in collect call with data.

**Smartphone (please complete the following information):**
 - Emulator, android 12

**Comment by digitalbuddha** [comment]
Hmm tough to tell. We have similar sample that is working. Check roomfragment in the app module. Could you also show your dao? Maybe query is wrong.

**Comment by kosiarska** [comment]
Yep, you're right. My query was wrong. So that's not a library bug. Is there a possibility to add some kind of logging capability to Store (like okhttp logger for example). Thanks for quick response.

**Comment by digitalbuddha** [comment]
Nothing exists currently but happy to take an external contribution 🙂

**Comment by kosiarska** [comment]
I'll try to find some free time to work on this.
