### ISSUE TITLE
Dependency fails to resolve

### ISSUE THREAD

**Issue by IkemNwodo** [dropbox/Store#42]
The dependency - implementation 'com.dropbox.mobile.store4:4.0.0-SNAPSHOT' failing to resolve. it is included in build.gradle(Module: app)
I need help fixing it.
@yigit  @digitalbuddha

**Comment by digitalbuddha** [comment]
Do you have maven snapshot repo included?

**Comment by IkemNwodo** [comment]
> Do you have maven snapshot repo included?

I'm sorry, i don't know how to do that. please could you point me to the steps?

**Comment by ychescale9** [comment]
In your root `build.gradle`:

```

allprojects {
    repositories {
        // Your other repositories...
        // Add maven snapshot repository
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}
```

**Comment by IAmDarush** [comment]
One more thing to add:

make sure you add the repository inside `allprojects` and not `buildscript`

```
allprojects {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }**// this works**
    }
}
```

and not:

```
buildscript {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" } **// this doesn't work**
    }
} 
```
