### ISSUE TITLE
[BUG] fetcher is not released correctly when coroutine scope is cancelled

### ISSUE THREAD

**Issue by lukisk** [dropbox/Store#429]
**Describe the bug**
When cancel active flow's scope, new subscribed flow from Store doesn't emit new items.

**Sample app**
Issue is recreated in sample app: https://github.com/lukisk/store-fetcher-issue

**To Reproduce**
1. Click on "Fresh" button - you can see updates in textview and logcat
2. Click on "Cancel" button
3. Again click on "Fresh" button - no updates, flow is "dead"

**Expected behavior**
New subscribed flow from store will emit new updates.

**Additional context**
I investigated it, and problem is in FetcherController, here is fix: https://github.com/lukisk/Store/commit/e968be960917a952856b6f02b106db1e3fc2ba2a
- there was no guarantee that Fetcher will be released in finally block.

**Comment by digitalbuddha** [comment]
Thanks for finding! Mind opening up a pr with the fix and by turning the sample into a unit test to prevent future regression?

**Comment by lukisk** [comment]
Yes, i can. Is not this test (https://github.com/lukisk/Store/commit/e968be960917a952856b6f02b106db1e3fc2ba2a#diff-e85d4a32510dca21577217985fd5ebd18cb936b536916a88e516385549b16c93) enough?

**Comment by digitalbuddha** [comment]
Looks good to me but let’s let others review when pr is open
