### ISSUE TITLE
better error messaging in flows that are created after multicast#close

### ISSUE THREAD

**Issue by yigit** [dropbox/Store#45]
right now we have a multicast#close function that closes the actor, making it useless.
After that point, any new downstream flow will receive closed channel exception.
We should instead send a more explicit exception so that developer can understand what happened.

**Comment by jossiwolf** [comment]
I'd love to take a look here - can you provide a code sample on how this happens? I'm still new to the codebase :)

**Comment by yigit** [comment]
Thanks.
Here is the simple repro:

```
val multicasted = Multicaster(...)
multicasted.flow.take(1).toList()
mutlicasted.close()
multicasted.flow.take(1).toList() // errros
```

The real use case where i want to close is two folds:
* We cache multicaster per key in Store Fetcher Controller and close them when none active. If we have a bug that would cause someone to resubscribe to that closed flow, they get a random channel closed exception.

* Another case where I need explicit close is transformations.

Assume i have some code like this:

```
val key = ConflatedBroadcastChannel<String>()
val data = key.asFlow().distinctUntilChanged().map {
    Multicaster(...)
}.scan (null) {prev,  next -> 
    prev?.close()
   next
}.flow
```

I basically want to have a shared flow based on a key but also close the previous one. In this case, i never leak the multicaster but assume `data` was not `.flow` but instead the Multicaster. Someone could hold a reference to it and subscribe even after it is closed.

I would like to get an explicit error in these cases so that they know what is going on instead of a random channel closed expection.

Lmk if this helps. Sorry i wrote the code w/o trying but should be fine hopefully :)

**Comment by yigit** [comment]
here is a similar case where it crashes although it should not:
not necessarily the same issue but adding here to give an idea.
```
@Test
    fun foo2() = testScope.runBlockingTest {
        val channel = Channel<Int>(Channel.UNLIMITED)
        val multicasted = Multicaster(
            scope = testScope,
            bufferSize = 1,
            source = channel.consumeAsFlow(),
            onEach = {},
            keepUpstreamAlive = true
        )
        val job = launch {
            multicasted.flow.onEach {
                println("received $it")
            }.onCompletion {
                println("done")
            }.toList()
        }
        channel.offer(1)
        channel.offer(2)
        multicasted.close()
        assertThat(job.isActive).isFalse()
    }
```

**Comment by yigit** [comment]
actually i think i'll just work on this.
needed to make some changes for paging
https://android-review.googlesource.com/c/platform/frameworks/support/+/1198679

will cherry pick them here and i may as well clarify close behavior while cherry picking it.

**Comment by jossiwolf** [comment]
I was about to write up some ways I think this could be implemented, but you probably have a better idea. Let me know if there are any other things you need help with!
