### ISSUE TITLE
Control persister maximum size

### ISSUE THREAD

**Issue by DanielAsher** [dropbox/Store#66]
I'm using `Store` with a persister implementation that uses android's `fun Context.getCacheDir()` to save media files to disk. Is there a way to control the maximum size or maximum number of these cached files?

**Comment by digitalbuddha** [comment]
I don't think there is a good generic way for us to handle controlling max size for persisters. To unpack a bit more what is your expectation when max size is reached? Should we throw an exception? Should we overwrite oldest made file or oldest accessed? Should we allow priority for some files to not get deleted? What if someone's persister is appending data to a single file and they want to control max size of that file? 

Personally, I'd recommend handling the logic yourself within the `read/write` function of your persister implementation

**Comment by DanielAsher** [comment]
@digitalbuddha Thanks for your speedy response. I think I misunderstood the scope of this project. I expected to find a built-in implementation of a `FileSystemPersister` and a `FileSystemPolicy` that mirrored the `MemoryPolicy`.

To answer your questions:

> Should we overwrite oldest made file or oldest accessed? 
This should be specified by a `FileSystemPolicy`
> Should we allow priority for some files to not get deleted? 
This should be specified by a `FileSystemPolicy`
> What if someone's persister is appending data to a single file and they want to control max size of that file?
This feels beyond the remit of a caching library.

Anyhow, thanks again for your explanation here.

**Comment by DanielAsher** [comment]
I would suggest that the documentation could be more explicit. In particular the following text from the README:
> You can also define how your Store will cache data in-memory and on-disk.

led me to think that file system caching policy was supported.
