### ISSUE TITLE
Feature Request: Report progressive Loading percentage

### ISSUE THREAD

**Issue by DanielAsher** [dropbox/Store#74]
Many long running data loads are able to report progress during the loading. This can allow for a better user experience as users can quickly estimate the time of a download, and take quicker action to check their connectivity if there is an interruption mid-load.

At first blush this seems to require new functionality in the `StoreBuilder` perhaps a `StoreBuilder.fromProgressive(fetcher: (key: Key) -> Flow<Progressive<Output>>)`. 

As an `InputStream` is most commonly buffered into a `FileOutputStream` to avoid loading the entire resource into memory, it would be the responsibility of the fetcher to write to disk.

It could be that this use case is beyond the scope of the project, in which case I humbly ask that this be advertised in the README, as it took quite a while to understand the current abilities of this library.

Thanks.

**Comment by digitalbuddha** [comment]
This feature would be too complicated to add without breaking changes, closing and will consider in next major version
