### ISSUE TITLE
Create configuration to not emit same disk and memory value 

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/Store#78]
Memory and disk caches can be out of sync. One scenario where this happens is when a store has 0 active collectors and a new value is saved to your source of truth. As a result we always emit disk and memory cache values one after the other whenever a cache value is requested. This is not ideal for consumers that don't have diffing. I'd like to add a store configuration that compares disk to memory and if they are the same then don't update and emit the memory value.

**Comment by yigit** [comment]
i'm torn on this a bit.
in one hand, i'd like to provide the expected case easy to support.
on the other hand, providing it is a new API that needs to be understood and also super easy to diff if the intent is to assume object equality in values. (literally one `distinctUntilChanged` operator if on the value).
also, do we only diff between cache and disk? why not network and cache/disk as well? (i assume it will also be common to fetch the exact same value).
that being said, maybe it goes into the bucket where you still want to know data is refreshed from server vs data between cache/disk is not really much of a concern.

**Comment by digitalbuddha** [comment]
closing as it can be handled with upstream operators
