### ISSUE TITLE
Modularize multicast implementation

### ISSUE THREAD

**Issue by realdadfish** [dropbox/Store#8]
It would be supercool if Store(4)'s [multicast implementation](https://github.com/dropbox/Store/tree/master/store/src/main/java/com/dropbox/android/external/store4/impl/multicast) could get modularized, so it would be fetchable separately in projects that do not use Store(4), but that need a `RxJava.share()` alternative in the coroutines world.

Thanks again for the fantastic talk at KotlinConf 2019!

**Comment by digitalbuddha** [comment]
Before pulling https://github.com/dropbox/Store/tree/master/store/src/main/java/com/dropbox/android/external/store4/impl/multicast into its own module I'd love to hear more about your use case. Primarily I'd like to add tests for your use case before moving it so that we cna verify it works for a more generic case.

Do you mind adding a pr with a tesf that shows your usage in a simplified manner?

**Comment by realdadfish** [comment]
I don't have a use case at hand, other than proprietary projects where I used Rx multicasting in the past. If this is a bummer for you, then I'm totally fine if you close this.

Otherwise I could just come up with some artificial use cases, where I'd concentrate on (sorry, rx terms still) ensuring that the upstream subscription keep only active as long as there are downstream subscribers are there and where I'd automatically re-subscribe to upstream in case a new subscriber comes in when no other is active.

Places I used sharing resources like this in the past was e.g. external API handling, where I got some connection handle that needed to be initialized and afterwards passed around as well as being closed in the end.

**Comment by yigit** [comment]
That seems fairly similar to our use case. I'll take a stab at this and then maybe you can try if it works for your case or not.

**Comment by ychescale9** [comment]
@elizarov mentioned at Kotlinconf that sharing and caching flows will be added (next year?). Does it still make sense to publish the current implementation as an artifact if we are planning to migrate to the stock one?

**Comment by digitalbuddha** [comment]
eh why not is my thought. We can always deprecate when it exists. This implementation is a bit specific to Store where consumers that do not get a value will have the upstream flow restart.
