### ISSUE TITLE
when we need to update local data soure?

### ISSUE THREAD

**Issue by anggit97** [dropbox/Store#80]
I little bit confuse, when we need to update local data soure if the local data is exists? is it just update when we try to refresh by action (ex: swipe refresh) ?

**Comment by eyalgu** [comment]
The local sourceOfTruth is meant to act as a local cache for the values coming from the server. There are 2 types of updates to it: 
1) From Store - When Store gets new network values (or `clear` is called) store will update the local source of truth with the new value that came back from the fetcher.
2) Outside of store - Store currently only support reading values (we have a discussion on how to  add write support in #25). If you update a value that's cached into store you should update that value in the local storage yourself and have it propagated to store via the source of truth. This is easy if you use Room as your source of truth as it will take care of sending updates to subscribers whenever you update a value.
