### ISSUE TITLE
What is the benefit of using stream vs just using the "convenience" .fresh or .get?

### ISSUE THREAD

**Issue by giancarlogatti** [dropbox/Store#84]
It says on the front page that the stream is the "primary function" provided by a store instance. 

Do I have it right that the main benefit is receiving a StoreResponse that contains a possible 3 different values making reacting to it easy? 

How would opening multiple flows work? If a user clicks on a button and StoreRequest.fresh() was called, does that create a brand new flow every single time the function is called? When does the flow stop the collection process?

**Comment by eyalgu** [comment]
There are 2 main benefits to `stream` over a single value:
1) As you say, you can get values from disk/cache/fetcher, which is useful if you want to first display a cached value while waiting for the fetcher to get a `fresh` value (this is the main use case covered by the `fresh` extension function).
2) Stream allows you to continue receiving updates to the data as it changes. If you use the data coming out of store to show a UI for example, by using stream you'll be able to always show the newest data. New data will be emitted if changes were made to the sourceOfTruth or if another request caused store to refetch the item you are streaming.

For your 2nd question:
Every call to `stream` (or `fresh`) will cause a new **cold** flow to be created (which will not cause any coroutine or other non-builder action to be performed). The action starts when you collect the flow (the equivalent of `subscribe` if you're coming from Rx world). Store, under the hood will coalesce all the fresh calls into a **single** fetcher call. Generally, store's `stream` should never be stopped by store, only by the user (though maybe there are some error conditions that we'll cause it to stop? if so we might want to fix those to make it clear store will emit until you're the collection is stopped by the user).

**Comment by giancarlogatti** [comment]
So what I'm hearing is that we can call StoreRequest.fresh() as much times as we want and when the collector is active it will start a new flow but we don't have to worry about deleting previous flow objects that were created from function calls. 

How does it work if we open both a fresh and cache stream? Calling fresh will also update the cache, which means that cache streams will also receive a new emission, which could introduce possible duplication of the displaying of the data to the UI.

**Comment by eyalgu** [comment]
> So what I'm hearing is that we can call StoreRequest.fresh() as much times as we want and when the collector is active it will start a new flow but we don't have to worry about deleting previous flow objects that were created from function calls.
Yes. You can collect for as long as you care about the results. The collection will be automatically cancelled when the collecting coroutine (or coroutine scope) is completed/cancelled.
> 
> How does it work if we open both a fresh and cache stream? Calling fresh will also update the cache, which means that cache streams will also receive a new emission, which could introduce possible duplication of the displaying of the data to the UI.
Fresh and cached refer to the initial results - is it ok to get a cached value? Should we avoid calling the fetcher? Etc. That does not affect subsequent update. If you asked to stream the data, that mean you will get all the updated that store knows about to the data your collecting until you stop the collection
