### ISSUE TITLE
Issue when mapping data in .fromNonFlow

### ISSUE THREAD

**Issue by giancarlogatti** [dropbox/Store#88]
```
private fun sensorMapping(sensor: SensorApi.Dto.SensorRecentResponse) =
        sensor.map()

    val store =
        StoreBuilder
            .fromNonFlow<StoreKey.SensorsKey, List<SensorData>> {
                remoteDataSource.getSensors().body()?.map(::sensorMapping)!!
            }
            .persister(
                reader = localDataSource::getSensors,
                writer = localDataSource::saveSensors
            ).cachePolicy(
                MemoryPolicy.builder()
                    .setMemorySize(100)
                    .setExpireAfterAccess(8)
                    .setExpireAfterTimeUnit(TimeUnit.DAYS)
                    .build()
            ).build()

```
We are getting the body that has our data as I've confirmed in a breakpoint but store isn't actually doing anything with it, so it isn't an issue with the endpoint. We are collecting the flow, but we set a breakpoint in the line:                 remoteDataSource.getSensors().body()?.map(::sensorMapping)!! and it doesn't even reach that breakpoint. 

It used to reach that breakpoint when it had this as the body in nonFlow:

val sensors = mutableListOf<SensorData>()
            remoteDataSource.getSensors().body()?.forEach {
                sensors.add(it.map())
            }
            sensors

But the problem with this was that it never reached the line sensors where we returned the list of sensors

**Comment by yigit** [comment]
can you show how you are collecting from the store? Also, if you can produce a simple app that reproduces the issue, that would be very helpful.  We have plenty of tests that use `fromNonFlow` (https://github.com/dropbox/Store/search?q=fromNonFlow&unscoped_q=fromNonFlow) so having a repro sample would help us understand what is going on.

**Comment by giancarlogatti** [comment]
Ok we are producing a simple app to replicate it but for now, we are collecting from it like this...

```
override fun cacheSensorStream(): Flow<StoreResponse<List<Entity.Sensor>>> =
        createSensorStream(StoreRequest.cached(StoreKey.SensorsKey(), true))

sensorRepository.cacheSensorStream().collect(flowCollector)
```

We basically add the things we collect to a live data object we are observing, we keep getting no data from the fetcher. 

We also realized we didn't add the store key in the body of nonFlow but that still didn't remedy the issue but it looks like this now...

`remoteDataSource.getSensors(it).body()?.map(::sensorMapping)!!
`

**Comment by giancarlogatti** [comment]
We made this sample app to demonstrate what we are experiencing with store..

https://github.com/vdtyson/StoreDemo

If you clone and test the app you won't get any data from the API being tested.

**Comment by yigit** [comment]
I've run the app and if you add a log tot he collector, you'll actually see:
```
val quoteCollector: FlowCollector<StoreResponse<QuoteData>> = object : FlowCollector<StoreResponse<QuoteData>> {
                override suspend fun emit(value: StoreResponse<QuoteData>) {

                    println("received $value") // <<<<<
                    when(value) {
                        is StoreResponse.Data -> {
                            textView_newQuote.text = value.value.quote
                        }
                        is StoreResponse.Error -> {
                            textView_newQuote.text = value.error.message
                        }
                    }
                }

            }
```

```
2020-02-03 23:18:17.236 14525-14525/com.versilistyson.storedemo I/System.out: received Loading(origin=Fetcher)
2020-02-03 23:18:18.299 14525-14525/com.versilistyson.storedemo I/System.out: received Error(error=kotlin.KotlinNullPointerException, origin=Fetcher)
```
the code gets an NPE because of this line in `QuoteRepository`:
`response.body()!!.map()`
which gets forwarded to your collector wrapped in a `StoreResponse.Error`.

**Comment by giancarlogatti** [comment]
Yeah we are fixing that, sorry should've looked into it more, new app we're pushing soon.

**Comment by giancarlogatti** [comment]
https://github.com/vdtyson/StoreDemo

Same link...not working, api call is successful inside the fetcher.

**Comment by yigit** [comment]
that one does not work because you've defined your DAO method as

```
@Update(onConflict = OnConflictStrategy.REPLACE)
suspend fun saveQuote(quoteToSave: QuoteData)
```

so it does not insert the data into database hence the read method fails to read it back.
changing it to `Insert` fixes your sample.

**Comment by giancarlogatti** [comment]
Thanks so much. If we lets say wanted to add a different quote to store we'd have to use a new key? Or would writing it using the previous key overwrite it in the dao/cache?

**Comment by yigit** [comment]
it depends. right now your query returns the first quote in the database (likely to be the very first inserted, but no guarantee by sqlite).

Can you explain what you are trying to do? Do you want to query w/ a specific quote id and get that quote or get all quotes ?

**Comment by vdtyson** [comment]
We're trying to query for the last quote id returned from the fetcher.

**Comment by vdtyson** [comment]
Also, every time the generate quote button is clicked, we'd like it to return a new value

**Comment by yigit** [comment]
so i think what you can do is, write your dao like this:

```
@Dao
interface QuoteDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun saveQuote(quoteToSave: QuoteData)

    @Query("SELECT * FROM quote_table ORDER BY rowId DESC LIMIT 1")
    fun readQuote(): Flow<QuoteData>

    @Delete
    fun deleteQuote(quoteToDelete: QuoteData)
}
```
Then your read method will always return the last "Edited/inserted" row from the database. Not sure if this is what you want in the long term as it will get invalidated every time a quote enters the database for any reason but this is the best I could think of unless you have to use another field for the quite that is fetched and query by it. That would be something like:

```
@Dao
interface QuoteDao {
    @Transaction
    suspend fun saveLatestQuote(quoteToSave: QuoteData) {
          unmarkLatestQuote()
          insert(quoteToSave.copy { latestQuote = true })
    }
    @Query("UPDATE QuoteData set latestQuote = 0 WHERE latestQuote = 1")
    suspend fun unmarkLatestQuote()
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun saveQuote(quoteToSave: QuoteData)

    @Query("SELECT * FROM quote_table WHERE latestQuote = 1 ORDER BY rowId DESC LIMIT 1")
    fun readQuote(): Flow<QuoteData>

    @Delete
    fun deleteQuote(quoteToDelete: QuoteData)
}
```
