### ISSUE TITLE
Is there any specific reason to install 3 different sample apps?

### ISSUE THREAD

**Issue by fgiris** [dropbox/Store#91]
When I run the sample app, there are 3 different apps installed for each activity (RedditActivity, RoomActivity and StreamActivity). Is there any reason to do that?

**Comment by yigit** [comment]
not really it is probably we've been adding launcher activities so they all become launcher icons (still 1 app though). Do you think it bothers, should we try to create 1 launcher activity that merges them ?

**Comment by fgiris** [comment]
I think it would be better to have one activity which merges them. Maybe having one activity and bottom nav bar with 3 different fragments would be better. I would be happy to take it.

**Comment by digitalbuddha** [comment]
We would appreciate the help! The samples definitely need some love

**Comment by rallat** [comment]
Thanks for the contribution 💯

**Comment by fgiris** [comment]
Anytime 👊🏻
