### ISSUE TITLE
Should we add support for fetcher/stream that fetches by range rather than key?

### ISSUE THREAD

**Issue by eyalgu** [dropbox/Store#94]
If we wanted Store to be the backing data source for paging, we would need to be able to fetch not by key, but by range.
@yigit what do you think? I haven't dug into Paging3 APIs yet (because the only way for me to do it now it to read the source code :)), but feels this is some thing that's missing right now (e.g #63).

**Comment by yigit** [comment]
i'm waiting for paging3 API to become more mature to start tackling this. It'll soon be EAP where we should have a better idea where everything fits.

Paging does similar things store do (sharing). It might be mostly letting people return `PagedData.share()` instances from store for one part.
For the data source of the paging, it might make sense to put store behind as well.

My plan is to first hand write it to see how it would look and then see if we have some ways to make it more smooth.
I don't think we'll need to add range as it won't be much different than a composite key. But again, this requires a lot more tinkering w/ before saying something proper.

**Comment by digitalbuddha** [comment]
@yigit you mentioned not much to gain with store/paging. Is that still the case? Should be close this?

**Comment by yigit** [comment]
lets keep it open, at least for now. Paging 3 is about to do an EAP that'll help us better finalize the APIs. I have a demo app where i'm trying to integrate both but last time i tried, the added value was none. 
I just don't want to pre-maturely close this one w/ o a final decision or at least a sample that shows why we won't do integration.
i'll assign it to me.

**Comment by digitalbuddha** [comment]
paging is out, I don't see any gain from a paging store. Closing
